# Generated by Django 5.2.8 on 2025-11-14 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cep', models.CharField(blank=True, max_length=20)),
                ('cidade', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fazendas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultura', models.CharField(max_length=100)),
                ('variedade', models.CharField(blank=True, max_length=100)),
                ('area_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_plantio', models.DateField(blank=True, null=True)),
                ('data_prevista_colheita', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to='farm.fazenda')),
            ],
        ),
    ]
