# Generated by Django 5.2.8 on 2025-11-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fazenda',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='fazenda',
            name='estado',
        ),
        migrations.AddField(
            model_name='fazenda',
            name='areacultivada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='fazenda',
            name='areatotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
