# Generated by Django 5.2.8 on 2025-11-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_remove_fazenda_cidade_remove_fazenda_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fazenda',
            name='cidade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fazenda',
            name='estado',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
