# Generated by Django 5.2.8 on 2025-11-18 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_culturainfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivar',
            name='cultura_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cultivares', to='farm.culturainfo'),
        ),
    ]
