# Generated by Django 5.2.8 on 2025-11-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultura', models.CharField(max_length=100)),
                ('variedade', models.CharField(blank=True, max_length=100)),
                ('origem', models.CharField(blank=True, max_length=255)),
                ('preco_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_kg', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
